---
- name: restart graylog-server
  ansible.builtin.service:
    name: graylog-server
    state: restarted

- name: restart graylog-datanode
  ansible.builtin.service:
    name: graylog-datanode
    state: restarted

- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
...
