---
- name: restart graylog-server
  service:
    name: graylog-server
    state: restarted

- name: restart graylog-datanode
  service:
    name: graylog-datanode
    state: restarted

- name: restart mongodb
  service:
    name: mongod
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
...
