---
- name: Install Graylog Repositry
  ansible.builtin.dnf:
    name: "{{ graylog_repo_rpm }}"
    disable_gpg_check: true

- name: Add MongoDB repository file
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/mongodb-org.repo
    content: |
      [mongodb-org-{{ mongodb_version }}]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
...
