---
# tasks file for joe-speedboat.nginx-rp
- name: install nginx packages
  ansible.builtin.dnf:
    name: '{{ item }}'
  with_items: '{{ nginx_packages }}'

- name: create /etc/nginx/nginx.conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: nginx
    mode: 640
  notify:
  - restart nginx

- name: create /etc/nginx/conf.d/ssl-offloading.conf
  ansible.builtin.template:
    src: ssl-offloading.conf.j2
    dest: /etc/nginx/conf.d/ssl-offloading.conf
    owner: root
    group: nginx
    mode: 0640
  notify:
  - restart nginx

- name: create /usr/local/sbin/create-cert.sh
  ansible.builtin.template:
    src: create-cert.sh.j2
    dest: /usr/local/sbin/create-cert.sh
    owner: root
    group: root
    mode: 0700

- name: Create self signed cert if needed
  ansible.builtin.shell:
    cmd: /usr/local/sbin/create-cert.sh
  changed_when: false

