---

- name: Install Graylog Repositry
  dnf:
    name: "{{ graylog_repo_graylog_rpm }}"
    disable_gpg_check: true

- name: Add MongoDB repository file
  copy:
    dest: /etc/yum.repos.d/mongodb-org.repo
    content: |
      [mongodb-org-{{ mongodb_version }}]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc

- name: Download OpenSearch repository file
  get_url:
    url: https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version }}/opensearch-{{ opensearch_version }}.repo
    dest: /etc/yum.repos.d/opensearch-{{ opensearch_version }}.repo

- name: Disable GPG check for OpenSearch repository
  lineinfile:
    path: /etc/yum.repos.d/opensearch-{{ opensearch_version }}.repo
    regexp: '^gpgcheck='
    line: 'gpgcheck=0'
    state: present

- name: Generate random password for OpenSearch
  set_fact:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ lookup('community.general.random_string', 32, special=True) }}"

- name: Install OpenSearch
  yum:
    name: opensearch
    state: present
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ OPENSEARCH_INITIAL_ADMIN_PASSWORD }}"

- name: Display the generated OpenSearch admin password
  debug:
    msg: "The initial OpenSearch admin password is {{ OPENSEARCH_INITIAL_ADMIN_PASSWORD }}"
...
